package com.cqqyd2014.mis4.domain;
// Generated 2018-3-25 9:40:41 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EbusinessOrderNoLen generated by hbm2java
 */
@Entity
@Table(name = "ebusiness_order_no_len", schema = "public")
public class EbusinessOrderNoLen implements java.io.Serializable {

	private EbusinessOrderNoLenId id;

	public EbusinessOrderNoLen() {
	}

	public EbusinessOrderNoLen(EbusinessOrderNoLenId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "EId", column = @Column(name = "e_id", nullable = false, length = 4)),
			@AttributeOverride(name = "orderNoLen", column = @Column(name = "order_no_len", nullable = false)) })
	public EbusinessOrderNoLenId getId() {
		return this.id;
	}

	public void setId(EbusinessOrderNoLenId id) {
		this.id = id;
	}

}
