package com.cqqyd2014.mis4.domain;
// Generated 2018-3-25 9:40:41 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VUserSendingNoWorking generated by hbm2java
 */
@Entity
@Table(name = "v_user_sending_no_working", schema = "public")
public class VUserSendingNoWorking implements java.io.Serializable {

	private VUserSendingNoWorkingId id;

	public VUserSendingNoWorking() {
	}

	public VUserSendingNoWorking(VUserSendingNoWorkingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 45)),
			@AttributeOverride(name = "snedingCount", column = @Column(name = "sneding_count")),
			@AttributeOverride(name = "id", column = @Column(name = "id", length = 36)),
			@AttributeOverride(name = "sendWeighting", column = @Column(name = "send_weighting", precision = 131089, scale = 0)) })
	public VUserSendingNoWorkingId getId() {
		return this.id;
	}

	public void setId(VUserSendingNoWorkingId id) {
		this.id = id;
	}

}
