package com.cqqyd2014.mis4.domain;
// Generated 2018-3-25 9:40:41 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VUserPickingWorking generated by hbm2java
 */
@Entity
@Table(name = "v_user_picking_working", schema = "public")
public class VUserPickingWorking implements java.io.Serializable {

	private VUserPickingWorkingId id;

	public VUserPickingWorking() {
	}

	public VUserPickingWorking(VUserPickingWorkingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "comId", column = @Column(name = "com_id", length = 4)),
			@AttributeOverride(name = "pickingCount", column = @Column(name = "picking_count")),
			@AttributeOverride(name = "id", column = @Column(name = "id", length = 36)),
			@AttributeOverride(name = "pickupWeighting", column = @Column(name = "pickup_weighting", precision = 131089, scale = 0)) })
	public VUserPickingWorkingId getId() {
		return this.id;
	}

	public void setId(VUserPickingWorkingId id) {
		this.id = id;
	}

}
